# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1q9sHUN5FqdsNx8FCUtwyu-IIv8KwdRcs
"""

karty=["2", "3", "4", "5", "6", "7", "8", "9", "10", "J", "Q", "K", "A"]
karty=4*karty
a=int(input("Podaj ilość talii: "))
karty=a*karty

o="t"
while o=="t":
  moja_1_karta=input("Podaj kartę nr1: ")
  moja_2_karta=input("Podaj kartę nr2: ")
  karta_dilera=input("Podaj kartę dilera: ")
  karty.remove(moja_1_karta)
  karty.remove(moja_2_karta)
  karty.remove(karta_dilera)
  if moja_1_karta=="J" or moja_1_karta=="Q" or moja_1_karta=="K" :
    moja_1_karta=10
  if moja_2_karta=="J" or moja_2_karta=="Q" or moja_2_karta=="K" :
    moja_2_karta=10
  if moja_1_karta=="A":
    moja_1_karta=11
  if moja_2_karta=="A":
    moja_2_karta=11
    moja_suma=int(moja_1_karta)+int(moja_2_karta)
    if moja_suma > 21:
      moja_2_karta=1
  moja_suma=int(moja_1_karta)+int(moja_2_karta)
  mozliwosci=0
  for i in karty:
    if i != "10":
      i=ord(i)-48
    else:
      i=10
    if i==17:
      i=11
      if moja_suma<=21:
        i=1
    if i>17:
      i=10
    if i+moja_suma<=21:
      mozliwosci=mozliwosci+1
  prawdopodobienstwo_nieprzegranej=100*mozliwosci/len(karty)

  print("Jeśli pociągniesz kartę to masz " + f"{prawdopodobienstwo_nieprzegranej:.1f}" + " procent szans na wyciągnięcie 21 lub mniej, a twoja suma to " + str(moja_suma))
  decyzja=input("Ciągniesz kartę? t/n: ")
  while decyzja=="t":
    if decyzja == "t":
      kolejna_karta=input("Podaj kartę którą wyciągnąłeś: ")
      karty.remove(kolejna_karta)
      if kolejna_karta=="J" or kolejna_karta=="Q" or kolejna_karta=="K" :
        kolejna_karta=10
      if kolejna_karta=="A":
        kolejna_karta=11
        moja_suma=moja_suma+int(kolejna_karta)
      if moja_suma > 21:
        moja_2_karta=1
      moja_suma=moja_suma+int(kolejna_karta)
    mozliwosci=0
    for i in karty:
      if i != "10":
        i=ord(i)-48
      else:
        i=10
      if i==17:
        i=11
        if moja_suma+11>21:
          i=1
      if i>17:
        i=10
      if i+moja_suma<=21:
        mozliwosci=mozliwosci+1
    prawdopodobienstwo_nieprzegranej=100*mozliwosci/len(karty)

    print("Jeśli pociągniesz kartę to masz " + f"{prawdopodobienstwo_nieprzegranej:.1f}" + " procent szans na wyciągnięcie 21 lub mniej, a twoja suma to " + str(moja_suma))
    decyzja=input("Ciągniesz kartę? t/n: ")
  if decyzja=="n":
    karta_dilera_2=input("Podaj kartę dilera: ")
    karty.remove(karta_dilera_2)
    if karta_dilera=="J" or karta_dilera=="Q" or karta_dilera=="K" :
      karta_dilera=10
    if karta_dilera_2=="J" or karta_dilera_2=="Q" or karta_dilera_2=="K" :
      karta_dilera_2=10
    if karta_dilera=="A":
      karta_dilera=11
    if karta_dilera_2=="A":
      karta_dilera_2=11
      suma_dilera=int(karta_dilera)+int(karta_dilera_2)
      if suma_dilera > 21:
        karta_dilera_2=1
    suma_dilera=int(karta_dilera)+int(karta_dilera_2)
    while suma_dilera<=16:
      kolejna_karta_dilera=input("Podaj kartę dilera: ")
      karty.remove(kolejna_karta_dilera)
      if kolejna_karta_dilera=="J" or kolejna_karta_dilera=="Q" or kolejna_karta_dilera=="K" :
        kolejna_karta_dilera=10
      if kolejna_karta_dilera=="A":
        kolejna_karta_dilera=11
        suma_dilera=suma_dilera+int(kolejna_karta_dilera)
      if suma_dilera > 21:
        kolejna_karta_dilera=1
      suma_dilera=suma_dilera+int(kolejna_karta_dilera)
  if moja_suma>suma_dilera and moja_suma<=21:
    print("Wygrałem, mam więcej niż diler")
  elif moja_suma==suma_dilera and moja_suma<=21:
    print("Na zero, remisik")
  elif moja_suma>21 or moja_suma<suma_dilera:
    print("Porażka, straciłeś kasiore")
  print(moja_suma)
  print(suma_dilera)
  o=str(input("Grasz dalej? t/n: "))